### ISSUE TITLE
Question: Possible to set start time on video?

### ISSUE THREAD

**Issue by michaeltoohig** [Elektordi/obs-websocket-py#24]
Is it possible for Media or VLC source to set the starting point in the media file or does the media file always play from the beginning? Kinda like the following.

```
'sourceSettings' : {'local_file': "path/to/file", 'start': 10.5}
```

I've asked the same at `obs-websocket` but I haven't heard if its possible yet and figured someone here may know.

https://github.com/Palakis/obs-websocket/issues/342

Thank you.

**Comment by Elektordi** [comment]
Sorry, we cannot implement this before Palakis work. obs-websocket-py is just an interface.
In the meantime, did you take a look at VLC source parameters? Or maybe cutting the video file before?

I'm closing this issue because I cannot do anything right now, please reopen it as soon as the feature is merged in obs-websocket master.
