### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by Elektordi** [Elektordi/obs-websocket-py#5]
Could be cool to have Py3 compat.
Putting an issue for this so people can follow up.

If there is some Py3 experts out there, feel free to take a look, never used it myself...

**Comment by JohnnyBlaze420** [comment]
I'm no Python 3 expert yet, but I'll try to help out. Two issues so far: exceptions and password hashing, both in core.py

Syntax for exceptions changed from
`except (ValueError, exceptions.ObjectError), e:`
in Python 2 to
`except (ValueError, exceptions.ObjectError) as e:`
in Python 3.

With those changes the module works if the user doesn't use a password. With the password provided we have another problem - hashing. core.py at line 57 and 58 throws an exception:
```
secret = base64.b64encode(hashlib.sha256(password + result['salt']).digest())
TypeError: Unicode-objects must be encoded before hashing
```
as strings in Python 3 are now fully unicode from the start. I tried to fiddle with it yesterday but didn't find a solution yet. Encoding the password string beforehand does raise a string + bytes can't concat bytes to str type error, so... Little bit of magic is required somewhere. :)

**Comment by KirillMysnik** [comment]
@JohnnyBlaze420 
Here's what I made it look like in [core.py](https://github.com/Elektordi/obs-websocket-py/blob/e4e5c37c41e08de15deb45419a74193e72ce0c00/obswebsocket/core.py#L103) (besides exception handling) to successfully connect to the secured OBS:

```python
secret = base64.b64encode(hashlib.sha256((password + result['salt']).encode('utf-8')).digest())
auth = base64.b64encode(hashlib.sha256(secret + result['challenge'].encode('utf-8')).digest()).decode('utf-8')
```

`auth` needs to be decoded from bytes because it will go to the JSONed dict, and JSON can only handle strings, not byte strings. So I decode the result from `b64encode` as a UTF-8. Well, in fact, it can be decoded as an ASCII, because that's just base64 string.

**Comment by Elektordi** [comment]
I definitely need Py2 compatibility because I originally write this lib for a specific task which is running under Py2.7

But I just read https://wiki.python.org/moin/Python2orPython3#Supporting_Python_2_and_Python_3_in_a_common_code_base and there is some interesting advices to have a common Py2/Py3 code.

obs-websocket-py is a pretty simple project, it should be possible to make it work. You think so?

**Comment by Elektordi** [comment]
I made some tests in python3 branch. Both samples seems to be working.
Could you test?

(Only `generate_classes.py` is still not working, urllib2 was not ported to Python3 yet. But it's not an important part of the project...)

**Comment by KirillMysnik** [comment]
Yes, it's possible to make it cross-pythonic. Usually the `six` package is used, but I think it's not even needed there.

`urllib2`'s just got refactored (or maybe just renamed) to [`urllib.request`](https://docs.python.org/3/library/urllib.request.html) in Python 3.

Since you mentioned `generate_classes.py`, I'ma open an issue related to it that I've discovered while trying to use `obs-websocket-py` for my needs.

**Comment by Elektordi** [comment]
Ok, made some tests with the python3 branch, no problems so far, I'm merging with master and aim at  release 0.3 to be advertised on PyPI as Py3 compliant... :)
